kind: pipeline
type: docker
name: default

steps:
- name: linter
  image: golang:latest
  environment:
    GOPROXY: https://goproxy.cn
  commands:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.27.0
  - golangci-lint run

- name: build
  image: golang:latest
  environment:
    GOPROXY: https://goproxy.cn
  commands:
  - go build

- name: docker
  image: plugins/docker
  settings:
  repo: yodstar/tunproxy
  use_cache: true
  username:
    from_secret: docker_username
  password:
    from_secret: docker_password
  tags:
  - latest
  when:
  event: push
  branch: master
